:PROPERTIES:
:ID:       627cc0e9-b179-447d-bef5-c505b011eb07
:END:
#+title: Action Hero
#+filetags: Idea
* Motivation

Searching "loop quantum gravity computation" on Web of Science yields zero results. This can't be because it's impossible; the first computational topology conference was when the subject was done in ALGOL, and differential geometry is just a fancy way of writing down PDEs, so there's no reason computational tools couldn't be developed.

Quantum gravity theories tend to have a somewhat mechanistic flow that may lend itself to automation:

- Define the action on a manifold

* Similar Work

[[https://books.google.com/books?hl=en&lr=&id=Zc4RAYFXYEgC&oi=fnd&pg=PA5&dq=computational+methods+in+differential+geometry&ots=nTT_PaXGcy&sig=qapOaMw6k3Gwu0dBo-h6qTa8ql4#v=onepage&q=computational%20methods%20in%20differential%20geometry&f=false][A Computational Differential Geometry Approach to Grid Generation]] may have some foundational notions of the representation of manifolds in computable terms.


* Feasibility

I've got enough of the math to make it somewhat possible. I'd be reading a lot of reviews though.

* Implementation

I'll need to talk to Agullo or one of the other LQG people about it, get their approval & reading recommendations, and have them loosely supervise progress. This would be ideal to supplement work with Chancellor over the summer.

** Specifics

The field of geometric analysis seeks to analyze geometric problems using methods from PDEs. Applying this formalism, we can study geometric problems numerically:
one of the ideas I had, inspired by the Atiyah-Singer index theorem's absurdly complicated invariants, is the proceedural generation of manifolds on which various invariants may be computed, in order to find candidate invariants or counterexamples for conjectured invariants.

This led me to the idea of developing a general computational differential geometry package (with something of an emphasis on the structures of mathematical physics).
