:PROPERTIES:
:ID:       af4e9fac-7233-4f27-a3dc-889d45637eb4
:END:
#+title: DIE
#+filetags: Musing
* Diversity, Inclusion, and Equity in Academia

The following I submitted to the LSU Department of Physics & Astronomy's Diversity, Equity, and Inclusion 2021-2022 climate survey:

Inclusion on the sole basis of immutable characteristics is often as harmful to historically victimized groups as exclusion has been. I hope everyone would agree there are no explicitly discriminatory policies in place in the department; should there be disagreement, I would like to know of the policy to fight for its removal. Any still-present disparity in representation is therefore due either to discrimination outside the department, present effects of past discrimination, or non-random variations in personal choice across groups; all of these no internal action of the department can control.

However, many institutions in attempts to rectify the perceived problem of such persistent disparities enact prejudicial policies to benefit historically victimized groups in lieu of policies based on ideals of merit and personal liberty. Such efforts for "diversity, inclusion, and equity" do far more harm than good to the groups they purport to serve. Impostor syndrome, all too common in any competitive enterprise, is only exacerbated when merit-based selection is discarded. Prejudice against the historically victimized is only more likely when objective metrics of competence are discarded; if a group's representation is 10% lower in the department than the population at large, is that more or less likely to produce prejudicial attitudes than exact representational parity if the average member from the group is less competent than their counterpart due to lowered objective standards? Will those denied for positions, scholarships, or tenure for entirely valid reasons not be driven more readily to prejudice and resentment for underrepresented populations as an outlet for the normal feelings of disappointment, concluding DIE efforts were responsible for their rejection?

I stand against prejudicial behavior and practices. However, explicitly forming a working group tasked with solving the alleged problems with diversity, inclusion, and equity in the department runs the risks associated with every bureaucracy, educational or governmental. Most worrying is the problem of regulatory capture, where those who call for the adoption of policy are a mixture of well-meaning activists and those who stand to gain from shaping the policy; the former are instrumental in gathering popular support for the policy, the resulting policy pays lip-service to the philosophical ideas the former hold dear but enacts changes that are all-to-easy for the latter to exploit to their own advantage, and by the time they do so, the activists have considered the good deed accomplished, and redirected their attention to the next cause-/de-rigueur/. In the governmental sphere, the examples are constant and shocking, from the ICC to the FDA and EPA. I worry the DIE initiatives that have become politically popular won't quickly devolve into a similar level of injustice, becoming kangaroo courts testing ideological purity run entirely by radicals of the kind populating communications departments, fulfilling George Wallace's dream of "segregation today, segregation tomorrow, segregation forever."
