:PROPERTIES:
:ID:       b2f87db2-9cd3-4d0e-9860-b011c516e9fa
:END:
#+title: Analytical Allegories
* Analytical Allegories

Fundamentally, human perception is through stories. Analytical philosophy, in my view the ultimately correct approach to philosophy, tends to emphasize the exactitude of methods. However, in order to bootstrap out and compare these methods, a small number of positions need to be established without relying methods with the exactitude analysis demands; for example, that there exist interesting questions to answer, that it is possible to obtain understanding through argument, that it is productive to do so, identification of the questions which need to be answered, and establishment of the criteria by which answers and arguments are to be compared.

This desire comes through reading into categorical structuralism in philosophy of mathematics, which advocates something like Lawvere's axiomatization of CAT with ECTS and topos theory studied via univalent type theory: while, given a mature understanding of mathematics, it seems feasible to implement, it seems much harder to motivate and teach it from foundations compared to more convential Bourbakian structuralism based on set theory. In a 2023 talk Topos Institute by Landry, it's asserted that there's a critical distinction between foundations and methodology. In seeking to rebut this, I was drawn to the pedagogical expedient of motivating methodology as foundation; upon reflection, though, it seems that a comparison between methodologies and foundations along these lines favors those which are based on the most accessible stories, real or otherwise.

In thinking about Austrian economics in relationship to my other analytical program, that of properly classifying the roles of science and mathematics along the lines of solutions to two different aspects of the problem of perception, I've arived at the conclusion that aspects of scientific and mathematical methodology are implicit in the category of action itself, and might be arived at /ab initio/ (not the entire methodology---the anarchy of Feyerabend in that regard still seems wise). It seems that here, too, the ultimate hallmark of success is if the program can truly be articulated to a student with little to no prior experience, or even with preconcieved notions antithetical to those advocated. The best course of action here, too, seems to be story.

All told, it seems that for the analyical program to achieve success, and contend with the worst excesses of the critical movement, it is necessary for it to advocate a small number of stories, metaphors, and allegories, possibly accompanied by intended interpretations, that're capable of bootstrapping out the principles on which the whole movement rests.
